### ISSUE TITLE
Python Tutorial

### ISSUE THREAD

**Issue by polunzh** [polunzh/todo#13]
(Python的手册)[http://www.pythondoc.com/pythontutorial3/]
而且还是中文的，总共16章，每天一章。
1. 开胃菜
2. 使用 Python 解释器
2.1. 调用 Python 解释器
2.1.1. 参数传递
2.1.2. 交互模式
2.2. 解释器及其环境
2.2.1. 源程序编码
3. Python 简介
3.1. 将 Python 当做计算器
3.1.1. 数字
3.1.2. 字符串
3.1.3. 列表
3.2. 编程的第一步
4. 深入 Python 流程控制
4.1. if 语句
4.2. for 语句
4.3. range() 函数
4.4. break 和 continue 语句, 以及循环中的 else 子句
4.5. pass 语句
4.6. 定义函数
4.7. 深入 Python 函数定义
4.7.1. 默认参数值
4.7.2. 关键字参数
4.7.3. 可变参数列表
4.7.4. 参数列表的分拆
4.7.5. Lambda 形式
4.7.6. 文档字符串
4.7.7. 函数注解
4.8. 插曲：编码风格
5. 数据结构
5.1. 关于列表更多的内容
5.1.1. 把链表当作堆栈使用
5.1.2. 把链表当作队列使用
5.1.3. 列表推导式
5.1.4. 嵌套的列表推导式
5.2. del 语句
5.3. 元组和序列
5.4. 集合
5.5. 字典
5.6. 循环技巧
5.7. 深入条件控制
5.8. 比较序列和其它类型
6. 模块
6.1. 深入模块
6.1.1. 作为脚本来执行模块
6.1.2. 模块的搜索路径
6.1.3. “编译的” Python 文件
6.2. 标准模块
6.3. dir() 函数
6.4. 包
6.4.1. 从 \* 导入包
6.4.2. 包内引用
6.4.3. 多重目录中的包
7. 输入和输出
7.1. 格式化输出
7.1.1. 旧式的字符串格式化
7.2. 文件读写
7.2.1. 文件对象方法
7.2.2. 使用 json 存储结构化数据
8. 错误和异常
8.1. 语法错误
8.2. 异常
8.3. 异常处理
8.4. 抛出异常
8.5. 用户自定义异常
8.6. 定义清理行为
8.7. 预定义清理行为
9. 类
9.1. 术语相关
9.2. Python 作用域和命名空间
9.2.1. 作用域和命名空间示例
9.3. 初识类
9.3.1. 类定义语法
9.3.2. 类对象
9.3.3. 实例对象
9.3.4. 方法对象
9.3.5. 类和实例变量
9.4. 一些说明
9.5. 继承
9.5.1. 多继承
9.6. 私有变量
9.7. 补充
9.8. 异常也是类
9.9. 迭代器
9.10. 生成器
9.11. 生成器表达式
10. Python 标准库概览
10.1. 操作系统接口
10.2. 文件通配符
10.3. 命令行参数
10.4. 错误输出重定向和程序终止
10.5. 字符串正则匹配
10.6. 数学
10.7. 互联网访问
10.8. 日期和时间
10.9. 数据压缩
10.10. 性能度量
10.11. 质量控制
10.12. “瑞士军刀”
11. 标准库浏览 – Part II
11.1. 输出格式
11.2. 模板
11.3. 使用二进制数据记录布局
11.4. 多线程
11.5. 日志
11.6. 弱引用
11.7. 列表工具
11.8. 十进制浮点数算法
12. 虚拟环境和包
12.1. 简介
12.2. 创建虚拟环境
12.3. 使用 pip 管理包
13. 接下来？
14. 交互式输入行编辑历史回溯
14.1. Tab 补全和历史记录
14.2. 其它交互式解释器
15. 浮点数算法：争议和限制
15.1. 表达错误
16. 附录
16.1. 交互模式
16.1.1. 错误处理
16.1.2. 可执行 Python 脚本
16.1.3. 交互式启动文件
16.1.4. 定制模块

**Comment by polun** [comment]
正在读刘鑫翻译的，准备看完。
